/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paad_wifi4us_utility_Constant */

#ifndef _Included_com_paad_wifi4us_utility_Constant
#define _Included_com_paad_wifi4us_utility_Constant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paad_wifi4us_utility_Constant
 * Method:    stringFromJNI
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_paad_wifi4us_utility_Constant_stringFromJNI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
